### ISSUE TITLE
How to Connect to the Database in the Docker Container?

### ISSUE THREAD

**Issue by toshikisugiyama** [Bajdzis/vscode-database#232]
I tried to connect to MySQL in the Docker container but I had a connection error.

![Image from Gyazo](https://i.gyazo.com/d19a91b6b5ecd654061b0c9e35c26518.png)

This is the `docker-compose.yml` file.

```
version: '3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
```

I named the service '**db**' so I input '**db**' as a host name.

I tried to input '**127.0.0.1**' or '**0.0.0.0**' but everything was failed.

Does anyone have an idea?

I appreciate any suggestions.

Thank you.
